# Generated by Django 5.2.7 on 2025-10-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.IntegerField(
                blank=True,
                help_text="Введите ваш телеграм chat_id",
                null=True,
                verbose_name="Чат айди телеграмма",
            ),
        ),
    ]
