# Generated by Django 5.2.7 on 2025-10-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ваш телеграм chat_id",
                max_length=255,
                null=True,
                verbose_name="Чат айди телеграмма",
            ),
        ),
    ]
