# Generated by Django 5.2.7 on 2025-11-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                default=123,
                help_text="Введите ваш телеграм chat_id",
                max_length=255,
                verbose_name="Чат айди телеграмма",
            ),
            preserve_default=False,
        ),
    ]
