# Generated by Django 5.2.7 on 2025-10-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
