# Generated by Django 5.2.7 on 2025-10-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="next_notification_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="дата и время следующего уведомления",
            ),
        ),
    ]
