# Generated by Django 5.2.7 on 2025-10-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_next_notification_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="next_notification_datetime",
            new_name="next_reminder",
        ),
    ]
