# Generated by Django 5.2.7 on 2025-10-23 05:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_rename_next_notification_datetime_habit_next_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default=datetime.time(18, 0), verbose_name="время действия"
            ),
        ),
    ]
