# Generated by Django 5.2.7 on 2025-10-24 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="continuation_time",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        120, message="Время выполнения не может превышать 120 секунд"
                    )
                ],
                verbose_name="время выполнения в секундах",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Частота не может быть меньше 1 дня"
                    ),
                    django.core.validators.MaxValueValidator(
                        7, message="Нельзя выполнять привычку реже, чем 1 раз в 7 дней"
                    ),
                ],
                verbose_name="периодичность в днях",
            ),
        ),
    ]
