# Generated by Django 5.2.7 on 2025-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_continuation_time_alter_habit_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="continuation_time",
            field=models.SmallIntegerField(verbose_name="время выполнения в секундах"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(verbose_name="периодичность в днях"),
        ),
    ]
